# Sourced by other scripts to load this host's connection details from
# host.toml into shell variables, without requiring a device profile to be
# selected. Split out of device.sh because pair-usb.sh/show-pair-qr.sh only
# ever need the host side -- device.sh's device-selection section requires
# config/devices/*.toml + config/active, which a fresh end user has neither
# of, and would otherwise abort these scripts before they get to do anything.
#
#   CONFIG_DIR=... source scripts/host-config.sh
#
# Sets: HOST_IP HOST_PORT VAAPI_RENDER_NODE PAIRING_TOKEN PAIRING_PUBKEY

: "${CONFIG_DIR:?host-config.sh requires CONFIG_DIR to be set before sourcing}"

# Minimal TOML reader: `_toml_get <file> <section> <key>`.
# Handles the flat `key = "value"` shape these profiles use -- not general TOML.
_toml_get() {
  awk -v section="$2" -v key="$3" '
    /^[[:space:]]*\[/ {
      gsub(/[][[:space:]]/, "", $0); current = $0; next
    }
    current == section {
      line = $0
      sub(/#.*/, "", line)                       # strip comments
      split(line, kv, "=")
      k = kv[1]; gsub(/[[:space:]]/, "", k)
      if (k == key) {
        v = substr(line, index(line, "=") + 1)
        gsub(/^[[:space:]]*"?|"?[[:space:]]*$/, "", v)
        print v; exit
      }
    }
  ' "$1"
}

HOST_CONFIG="$CONFIG_DIR/host.toml"
if [ ! -f "$HOST_CONFIG" ]; then
  echo "error: missing $HOST_CONFIG" >&2
  echo "  cp host.example.toml $HOST_CONFIG   (or ./install.sh, which does this)" >&2
  return 1 2>/dev/null || exit 1
fi
HOST_IP="$(_toml_get "$HOST_CONFIG" host ip)"
HOST_PORT="$(_toml_get "$HOST_CONFIG" host port)"
VAAPI_RENDER_NODE="$(_toml_get "$HOST_CONFIG" gpu vaapi_render_node)"
# Generated by palmtopd on first run (see palmtop-config's HostConfig::load)
# and appended to this file -- empty here means the daemon hasn't run yet.
PAIRING_TOKEN="$(_toml_get "$HOST_CONFIG" pairing token)"
PAIRING_PUBKEY="$(_toml_get "$HOST_CONFIG" pairing noise_public_key)"
# Blank ip means auto-detect.
if [ -z "$HOST_IP" ]; then
  HOST_IP="$(ip route get 8.8.8.8 2>/dev/null | grep -oP 'src \K\S+' | head -1)"
fi

export HOST_IP HOST_PORT VAAPI_RENDER_NODE PAIRING_TOKEN PAIRING_PUBKEY
