#!/usr/bin/env bash
# Inspects this machine and prints a ready-to-paste host profile.
#
#   ./scripts/probe-host.sh > config/host.toml
set -euo pipefail

IP="$(ip route get 8.8.8.8 2>/dev/null | grep -oP 'src \K\S+' | head -1 || true)"

# Prefer an integrated GPU render node for VA-API: on hybrid laptops the iGPU is
# usually the better encode target (always powered, no dGPU wake cost).
PICKED=""
for node in /dev/dri/renderD*; do
  [ -e "$node" ] || continue
  drv="$(grep -h DRIVER "/sys/class/drm/$(basename "$node")/device/uevent" 2>/dev/null | cut -d= -f2)"
  case "$drv" in
    amdgpu|i915|xe) PICKED="$node"; break ;;
  esac
  [ -z "$PICKED" ] && PICKED="$node"
done
[ -z "$PICKED" ] && PICKED="/dev/dri/renderD128"

cat <<EOF
# Generated by scripts/probe-host.sh on $(date -I)
# Machine-specific -- gitignored. See config/README.md

[host]
# Leave blank to auto-detect at runtime instead of pinning.
ip   = "$IP"
port = 9999

[gpu]
# Detected render nodes on this machine:
$(for n in /dev/dri/renderD*; do
    [ -e "$n" ] || continue
    d="$(grep -h DRIVER "/sys/class/drm/$(basename "$n")/device/uevent" 2>/dev/null | cut -d= -f2)"
    echo "#   $n -> $d"
  done)
vaapi_render_node = "$PICKED"

[encode]
codec = "h264_vaapi"
qp    = 24
fps   = 30
EOF
