#!/usr/bin/env bash
# Reads a connected phone and prints a ready-to-paste device profile.
#
#   ./scripts/probe-device.sh <adb-serial> > config/devices/my-phone.toml
#
# Find the serial with: adb devices -l
set -euo pipefail

SERIAL="${1:-}"
if [ -z "$SERIAL" ]; then
  echo "usage: $0 <adb-serial>" >&2
  echo >&2
  echo "Connected devices:" >&2
  adb devices -l 2>/dev/null | tail -n +2 | sed 's/^/  /' >&2
  exit 1
fi

a() { adb -s "$SERIAL" "$@"; }

MODEL="$(a shell getprop ro.product.model | tr -d '\r')"
SDK="$(a shell getprop ro.build.version.sdk | tr -d '\r')"
NAME="$(echo "$MODEL" | tr '[:upper:] ' '[:lower:]-' | tr -cd 'a-z0-9-')"

SIZE="$(a shell wm size | tr -d '\r' | grep -oE '[0-9]+x[0-9]+' | tail -1)"
WIDTH="${SIZE%x*}"; HEIGHT="${SIZE#*x}"
DENSITY="$(a shell wm density | tr -d '\r' | grep -oE '[0-9]+' | tail -1)"

# Peak refresh rate the panel advertises -- sets display quantisation in the
# latency budget (a 90Hz panel is ~11ms, not the 16ms a 60Hz panel implies).
REFRESH="$(a shell dumpsys display 2>/dev/null | grep -oE 'fps=[0-9.]+' \
  | grep -oE '[0-9.]+' | sort -rn | head -1)"
[ -z "$REFRESH" ] && REFRESH=60

# Vendor low-latency decoders, if present.
CODECS="$(a shell 'cat /vendor/etc/media_codecs*.xml 2>/dev/null' | tr -d '\r' || true)"
H264_LL="$(echo "$CODECS" | grep -oE '"[^"]*avc[^"]*low_latency[^"]*"' | tr -d '"' | head -1)"
H265_LL="$(echo "$CODECS" | grep -oE '"[^"]*hevc[^"]*low_latency[^"]*"' | tr -d '"' | head -1)"

# If connected wirelessly the serial is already ip:port; else ask the device.
if [[ "$SERIAL" == *:* ]]; then
  IP="${SERIAL%%:*}"
else
  IP="$(a shell ip route 2>/dev/null | tr -d '\r' | grep -oP 'src \K\S+' | head -1)"
fi

cat <<EOF
# Generated by scripts/probe-device.sh on $(date -I)
# Device-specific -- gitignored. See config/README.md

[device]
name  = "$NAME"
model = "$MODEL"
sdk   = $SDK

[adb]
serial = "$SERIAL"
ip     = "$IP"

[display]
width      = $WIDTH
height     = $HEIGHT
density    = $DENSITY
refresh_hz = $REFRESH

[decoder]
h264 = "$H264_LL"
h265 = "$H265_LL"

[limits]
# Starting point, not a measurement. Exceeding a device's decode capacity raises
# latency even while throughput still looks fine -- confirm with the decode spike
# before raising these.
max_width  = 1920
max_height = 1080
max_fps    = 30
EOF
